services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#   Example:
#   Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportCronModule:
#       tags:
#           - { name: shopsys.cron, hours: '*', minutes: '*' }
