_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix: /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix: /_profiler

_main:
    resource: routing.yml

shopsys_frontend_api_graphiql:
    resource: "@ShopsysFrontendApiBundle/Resources/config/routing_dev.yml"
    prefix: /graphql
