shopsys_shop_front:
    resource: "@ShopsysShopBundle/Resources/config/routing_front.yml"
    prefix: /

shopsys_shop_admin:
    resource: "@ShopsysShopBundle/Controller/Admin"
    prefix: /admin
    type: annotation

shopsys_shop_api_v1:
    resource: "@ShopsysShopBundle/Controller/Api/V1"
    prefix: /api/v1
    type: annotation
