front_homepage:
    path: /

front_export_personal_data:
    path: /personal-overview-export/xml/{hash}
    defaults:
        _controller: App\Controller\Front\PersonalDataController::exportXmlAction
        type: ~

front_download_uploaded_file:
    path: /file/{uploadedFileId}/{uploadedFilename}
    defaults: { _controller: App\Controller\Front\UploadedFileController::downloadAction }
    methods: [GET]
    requirements:
        uploadedFileId: \d+
