PaymentMutation:
    type: object
    config:
        fields:
            PayOrder:
                type: PaymentSetupCreationData!
                description: "Pay order(create payment transaction in payment gateway) and get payment setup data for redirect or creating JS payment gateway layer"
                args:
                    orderUuid:
                        type: "Uuid!"
                resolve: "@=mutation('payOrderMutation', args)"
            UpdatePaymentStatus:
                type: "PaymentStatus!"
                description: "check payment status of order after callback from payment service"
                args:
                    orderUuid:
                        type: "Uuid!"
                    orderPaymentStatusPageValidityHash:
                        type: "String"
                resolve: "@=mutation('updatePaymentStatusMutation', args)"
