framework:
    messenger:
        reset_on_message: true
        buses:
            messenger.bus.default:
                middleware:
                    - 'Shopsys\FrameworkBundle\Component\Messenger\DelayedEnvelope\DelayEnvelopeMiddleware'
        transports:
            example_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                    exchange:
                        name: example_exchange
                        type: direct
                    queues:
                        example_queue: ~
            placed_order_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                    exchange:
                        name: placed_order_exchange
                        type: direct
                    queues:
                        placed_orders: ~
                retry_strategy:
                    max_retries: 5
                    delay: 60000
                    multiplier: 5

        routing:
            Shopsys\FrameworkBundle\Component\Messenger\ExampleMessage: example_transport
            Shopsys\FrameworkBundle\Model\Order\Messenger\PlacedOrderMessage: placed_order_transport
