framework:
    messenger:
        reset_on_message: true
        failure_transport: failed
        buses:
            messenger.bus.default:
                middleware:
                    - 'Shopsys\FrameworkBundle\Component\Messenger\DelayedEnvelope\DelayEnvelopeMiddleware'
        transports:
            failed: 'doctrine://default?queue_name=failed'
            product_recalculation:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                    exchange:
                        name: product_recalculation
                        type: direct
                    queues:
                        product_recalculation: ~
            placed_order_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(MESSENGER_TRANSPORT_VHOST)%'
                    exchange:
                        name: placed_order_exchange
                        type: direct
                    queues:
                        placed_orders: ~
                retry_strategy:
                    max_retries: 5
                    delay: 60000
                    multiplier: 5

        routing:
            Shopsys\FrameworkBundle\Model\Product\Recalculation\ProductRecalculationMessage: product_recalculation
            Shopsys\FrameworkBundle\Model\Product\Recalculation\DispatchAllProductsMessage: product_recalculation
            Shopsys\FrameworkBundle\Model\Order\Messenger\PlacedOrderMessage: placed_order_transport
