# See the configuration reference at https://github.com/scheb/2fa/blob/master/doc/configuration.md
scheb_two_factor:

    email:
        digits: 6
        enabled: true
        mailer:
            'Shopsys\FrameworkBundle\Model\Administrator\Mail\TwoFactorAuthenticationMailFacade'
        template: '@ShopsysFramework/Admin/Content/Login/LoginFormTwoFA.html.twig'
    google:
        digits: 6
        enabled: true
        issuer: Shopsys
        server_name: Shopsys Platform
        template: '@ShopsysFramework/Admin/Content/Login/LoginFormTwoFA.html.twig'
        window: 1
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
